const fs = require("fs");
const palette = require("../styles/palette");

const cssContent = 
`/* This file is automatically generated by src/scripts/generate.ts */

@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
    --background: #ffffff;
    --foreground: #171b21;

    --muted: #f1f5f9;
    --muted-foreground: #64748b;

    --popover: #ffffff;
    --popover-foreground: #171b21;

    --border: #e2e8f0;
    --input: #e2e8f0;

    --card: #ffffff;
    --card-foreground: #171b21;

    --primary: #171b21;
    --primary-foreground: #c7ccd1;

    --secondary: #f1f5f9;
    --secondary-foreground: #171b21;

    --accent: #f1f5f9;
    --accent-foreground: #171b21;

    --destructive: #ff0000;
    --destructive-foreground: #c7ccd1;

    --ring: #94a3b8;

    --radius: 0.6rem;
    --font-sans: "Lato", sans-serif;
  }

  .hm-dark {
    --background: #171b21;
    --foreground: #e1e7ef;

    --muted: #0f1629;
    --muted-foreground: #7f8ea3;

    --popover: #171b21;
    --popover-foreground: #94a3b8;

    --border: #30353b;
    --input: #30353b;

    --card: #171b21;
    --card-foreground: #e1e7ef;

    --primary: #e1e7ef;
    --primary-foreground: #171b21;

    --secondary: #171b21;
    --secondary-foreground: #c7ccd1;

    --accent: #30353b;
    --accent-foreground: #c7ccd1;

    --destructive: #811d1d;
    --destructive-foreground: #c7ccd1;

    --ring: #30353b;
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
    font-feature-settings:
      "rlig" 1,
      "calt" 1;
  }
}
`;

fs.writeFile("src/global.css", cssContent, (err) => {
  if (err) {
    console.error("Error writing file:", err);
    return;
  }
  console.log("global.css file generated successfully.");
});
